const D=DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let level="all",filter="all",theme=D.themes[0],flashI=0,dictI=0,artI=0,orderI=0,mega=[],mi=0,ms=0,exam="picture",emailI=0,picI=0,spI=0,readI=0,atI=0;
const sh=a=>[...a].sort(()=>Math.random()-.5),norm=s=>s.toLowerCase().trim().replace(/[.,!?;:]/g,"").replace(/\s+/g," ");
const setOf=k=>new Set(JSON.parse(localStorage.getItem(k)||"[]"));const saveSet=(k,s)=>localStorage.setItem(k,JSON.stringify([...s]));
function speak(t){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="de-DE";u.rate=.86;speechSynthesis.speak(u)}window.speak=speak;
function openTab(id){$$(".panel").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$("#sidebar").classList.remove("open");scrollTo({top:0,behavior:"smooth"});if(id==="daily")renderDaily();if(id==="review")renderReview()}window.openTab=openTab;$$("[data-tab]").forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$$(".lv").forEach(b=>b.onclick=()=>{$$(".lv").forEach(x=>x.classList.remove("active"));b.classList.add("active");level=b.dataset.level;renderAll()});const fit=l=>level==="all"||l===level;
function toggle(k,id){let s=setOf(k),v=String(id);s.has(v)?s.delete(v):s.add(v);saveSet(k,s);renderVocab();renderReview();updateProgress()}
function updateProgress(){let known=setOf("knownWords"),p=Math.round(known.size/D.words.length*100);$("#sidePct").textContent=p+"%";$("#sideKnown").textContent=`${known.size}/${D.words.length}`;$("#sideBar").style.width=p+"%";$("#heroWords").textContent=D.words.length;$("#heroRules").textContent=D.rules.length}
function card(w){let k=setOf("knownWords"),s=setOf("savedWords"),h=setOf("hardWords");return `<article class="vocab-card"><div class="vocab-head"><div><div class="badges"><span class="badge">${w.level}</span><span class="badge">${w.pos}</span><span class="badge">${w.theme}</span></div><h3 class="de">${w.word}</h3><div class="meaning">${w.meaning}</div><p>${w.usage||""}</p></div><button class="speak" onclick='speak(${JSON.stringify(w.word)})'>🔊</button></div><div class="level-examples">${["A1","A2","B1"].map(l=>{let e=w.examples[l],de=typeof e==="string"?e:e.de,ar=typeof e==="string"?"":e.ar;return `<div class="example"><b>${l}</b><p class="de">${de} <button class="speak" onclick='speak(${JSON.stringify(de)})'>🔊</button></p><p class="ar">${ar}</p></div>`}).join("")}</div><div class="word-actions"><button class="mini-btn ${k.has(String(w.id))?"on":""}" onclick="toggle('knownWords',${w.id})">✓ محفوظة</button><button class="mini-btn ${s.has(String(w.id))?"on":""}" onclick="toggle('savedWords',${w.id})">★ مفضلة</button><button class="mini-btn ${h.has(String(w.id))?"on":""}" onclick="toggle('hardWords',${w.id})">! صعبة</button></div></article>`}
function renderVocab(){let q=$("#wordSearch").value.toLowerCase().trim(),rows=D.words.filter(w=>fit(w.level)&&(w.word+" "+w.meaning+" "+w.theme).toLowerCase().includes(q));let k=setOf("knownWords"),s=setOf("savedWords"),h=setOf("hardWords");if(filter==="known")rows=rows.filter(w=>k.has(String(w.id)));if(filter==="saved")rows=rows.filter(w=>s.has(String(w.id)));if(filter==="hard")rows=rows.filter(w=>h.has(String(w.id)));$("#wordGrid").innerHTML=rows.slice(0,250).map(card).join("")+ (rows.length>250?`<div class="feedback">يوجد ${rows.length-250} نتيجة إضافية. استخدم البحث أو اختيار المستوى لتضييق النتائج.</div>`:"")}
$("#wordSearch").oninput=renderVocab;$$("[data-filter]").forEach(b=>b.onclick=()=>{$$("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderVocab()});
function renderDaily(){let ts=D.themes.filter(t=>D.words.some(w=>w.theme===t&&fit(w.level)));$("#themeTabs").innerHTML=ts.slice(0,20).map((t,i)=>`<button class="theme-btn ${t===theme?"active":""}" data-theme="${t}">${t}</button>`).join("");if(!ts.includes(theme))theme=ts[0];let rows=D.words.filter(w=>fit(w.level)&&w.theme===theme).slice(0,80);$("#dailyGrid").innerHTML=rows.map(card).join("");$$("[data-theme]").forEach(b=>b.onclick=()=>{theme=b.dataset.theme;renderDaily()})}
function renderGrammar(){$("#grammarGrid").innerHTML=D.rules.filter(r=>fit(r.level)).map(r=>`<article class="grammar-card"><span class="badge">${r.level}</span><h3>${r.title}</h3><p>${r.text}</p></article>`).join("")}
function renderUnits(){$("#unitGrid").innerHTML=D.units.filter(u=>fit(u.level)).map(u=>`<article class="unit-card"><span class="badge">${u.level}</span><span class="badge">${u.xp} XP</span><h3>${u.title}</h3><p>${u.subtitle}</p><small>${u.ruleTitle||""}</small><br><button onclick="openTab('vocab')">فتح الكلمات</button></article>`).join("")}
function renderPron(){let list=D.pronunciation||[];$("#pronList").innerHTML=list.map(x=>`<article class="pron-card"><h3 class="de">${x.pattern}</h3><p>${x.hint}</p><p class="de">${x.examples.join ? x.examples.join(", ") : x.examples}</p><button class="speak" onclick='speak(${JSON.stringify((x.examples.join?x.examples[0]:x.examples.split(",")[0]))})'>🔊 اسمع</button></article>`).join("")}
window.startSpeechTimer=n=>{let e=$("#speechTimer");e.textContent=n+" s";let t=setInterval(()=>{n--;e.textContent=n>0?n+" s":"Fertig!";if(n<=0)clearInterval(t)},1000)}
function renderPractice(mode){let s=$("#practiceStage");if(mode==="flash"){let rows=D.words.filter(w=>fit(w.level));let w=rows[flashI%rows.length];s.innerHTML=`<div class="question">Flashcard</div><h2 class="de">${w.word}</h2><div class="meaning">${w.meaning}</div><p class="de">${w.examples.A2.de||w.examples.A2}</p><button class="speak" onclick='speak(${JSON.stringify(w.word)})'>🔊</button><div class="actions"><button id="nextF">التالي</button></div>`;$("#nextF").onclick=()=>{flashI++;renderPractice("flash")}}
if(mode==="dictation"){let rows=D.dictation.filter(x=>fit(x.level));if(!rows.length)rows=D.dictation;let x=rows[dictI%rows.length];s.innerHTML=`<span class="badge">${x.level}</span><div class="question">اسمع ثم اكتب</div><button id="playD">🔊 تشغيل</button><p>${x.hint}</p><input id="dictInput" style="width:100%" placeholder="اكتب الجملة بالألماني"><div class="actions"><button id="checkD">تحقق</button><button id="nextD" class="secondary">التالي</button></div><div id="fd"></div>`;$("#playD").onclick=()=>speak(x.text);$("#checkD").onclick=()=>$("#fd").innerHTML=`<div class="feedback">${norm($("#dictInput").value)===norm(x.text)?"✅ صحيح":"❌"}<p class="de">${x.text}</p></div>`;$("#nextD").onclick=()=>{dictI++;renderPractice("dictation")}}
if(mode==="article"){let rows=D.words.filter(w=>w.pos==="Nomen"&&["der","die","das"].includes(w.word.split(" ")[0])&&fit(w.level));if(!rows.length)rows=D.words.filter(w=>w.pos==="Nomen"&&["der","die","das"].includes(w.word.split(" ")[0]));let w=rows[artI%rows.length],p=w.word.split(" "),a=p.shift(),noun=p.join(" ");s.innerHTML=`<div class="question de">___ ${noun}</div><p>${w.meaning}</p><div class="options">${["der","die","das"].map(o=>`<button data-o="${o}">${o}</button>`).join("")}</div><div id="fa"></div>`;s.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>{let ok=b.dataset.o===a;b.classList.add(ok?"correct":"wrong");$("#fa").innerHTML=`<div class="feedback">${ok?"✅ Richtig":"❌ "+a+" "+noun}</div>`;setTimeout(()=>{artI++;renderPractice("article")},800)})}
if(mode==="reorder"){let rows=D.reorder.filter(x=>fit(x.level));if(!rows.length)rows=D.reorder;let x=rows[orderI%rows.length],chosen=[];s.innerHTML=`<div class="question">رتب الجملة</div><div id="build" class="feedback"></div><div class="options">${sh(x.words).map(w=>`<button>${w}</button>`).join("")}</div><div class="actions"><button id="checkO">تحقق</button><button id="nextO" class="secondary">التالي</button></div><div id="fo"></div>`;s.querySelectorAll(".options button").forEach(b=>b.onclick=()=>{chosen.push(b.textContent);b.disabled=true;$("#build").textContent=chosen.join(" ")});$("#checkO").onclick=()=>$("#fo").innerHTML=`<div class="feedback">${norm(chosen.join(" "))===norm(x.answer)?"✅ صحيح":"❌"}<p class="de">${x.answer}</p></div>`;$("#nextO").onclick=()=>{orderI++;renderPractice("reorder")}}
if(mode==="mega"){startMega()}}
$$("[data-practice]").forEach(b=>b.onclick=()=>renderPractice(b.dataset.practice));
function startMega(){let pool=D.quiz.filter(q=>fit(q.level));mega=sh(pool).slice(0,Math.min(25,pool.length));mi=0;ms=0;showMega()}function showMega(){let s=$("#practiceStage");if(mi>=mega.length){let p=Math.round(ms/mega.length*100);s.innerHTML=`<div style="text-align:center"><h2 style="font-size:56px;color:var(--accent)">${p}%</h2><p>${ms}/${mega.length}</p><button onclick="startMega()">إعادة</button></div>`;return}let x=mega[mi];s.innerHTML=`<span class="badge">${x.level}</span><div class="question">${x.q}</div><div class="options">${sh(x.options).map(o=>`<button data-o="${o.replace(/"/g,"&quot;")}">${o}</button>`).join("")}</div><div id="fm"></div>`;s.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>{let ok=b.dataset.o===x.a;if(ok)ms++;b.classList.add(ok?"correct":"wrong");$("#fm").innerHTML=`<div class="feedback">${ok?"✅":"❌"} ${x.why}<br><button id="nm">التالي</button></div>`;$("#nm").onclick=()=>{mi++;showMega()}})}window.startMega=startMega;
function renderExam(mode=exam){exam=mode;$$(".exam-tab").forEach(b=>b.classList.toggle("active",b.dataset.exam===mode));let s=$("#examStage");
if(mode==="picture"){let x=D.pictureTasks[picI%D.pictureTasks.length];s.innerHTML=`<div class="exam-visual"><img src="./assets/bildbeschreibung-see.jpg" alt="Bildbeschreibung: Menschen an einem See"><div><span class="badge">${x.level}</span><h3>${x.title}</h3><div class="prompt-list">${x.prompts.map(p=>`<div>${p}</div>`).join("")}</div></div></div><h4>Nützliche Ausdrücke</h4><div class="theme-tabs">${x.phrases.map(p=>`<span class="theme-btn">${p}</span>`).join("")}</div><button onclick="startSpeechTimer(60)">ابدأ دقيقة وصف</button><div id="speechTimer" class="timer"></div>`}
if(mode==="email"){let x=D.emailTasks[emailI%D.emailTasks.length];s.innerHTML=`<span class="badge">${x.level}</span><h3>${x.title}</h3><p>${x.situation}</p><div class="email-editor"><textarea id="mailText" placeholder="Schreib hier..."></textarea></div><div class="actions"><button id="showModel">Musterlösung</button><button id="nextMail" class="secondary">التالي</button></div><div id="mailModel"></div>`;$("#showModel").onclick=()=>$("#mailModel").innerHTML=`<div class="feedback"><pre style="white-space:pre-wrap">${x.model}</pre></div>`;$("#nextMail").onclick=()=>{emailI++;renderExam("email")}}
if(mode==="speaking"){let x=D.speakingTasks[spI%D.speakingTasks.length];s.innerHTML=`<img src="./assets/sprechen-trainer.jpg" style="width:100%;max-height:300px;object-fit:cover;border-radius:17px"><span class="badge">${x.level}</span><div class="question de">${x.question}</div><div class="prompt-list">${x.tips.map(t=>`<div>${t}</div>`).join("")}</div><button onclick="startSpeechTimer(${x.time})">ابدأ ${x.time} ثانية</button><div id="speechTimer" class="timer"></div>`}
if(mode==="reading"){let x=D.readingTasks[readI%D.readingTasks.length];s.innerHTML=`<span class="badge">${x.level}</span><h3>${x.title}</h3><p class="de">${x.text}</p>${x.questions.map((q,i)=>`<div class="feedback"><b>${q.q}</b><div class="options">${q.options.map(o=>`<button data-ri="${i}" data-o="${o}">${o}</button>`).join("")}</div></div>`).join("")}`;s.querySelectorAll("[data-ri]").forEach(b=>b.onclick=()=>{let q=x.questions[Number(b.dataset.ri)];b.classList.add(b.dataset.o===q.a?"correct":"wrong")})}
if(mode==="austria"){let x=D.austriaQuestions[atI%D.austriaQuestions.length];s.innerHTML=`<img src="./assets/oesterreich-werte.jpg" style="width:100%;max-height:290px;object-fit:cover;border-radius:17px"><div class="question de">${x.q}</div><div class="options">${x.options.map(o=>`<button data-o="${o}">${o}</button>`).join("")}</div><div id="fw"></div>`;s.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>{let ok=b.dataset.o===x.a;b.classList.add(ok?"correct":"wrong");$("#fw").innerHTML=`<div class="feedback">${ok?"✅":"❌ "+x.a}<br>${x.info}</div>`})}}
$$(".exam-tab").forEach(b=>b.onclick=()=>renderExam(b.dataset.exam));
function renderReview(){let h=setOf("hardWords"),s=setOf("savedWords"),k=setOf("knownWords");$("#reviewSummary").innerHTML=`<div><b>${h.size}</b>صعبة</div><div><b>${s.size}</b>مفضلة</div><div><b>${k.size}</b>محفوظة</div>`;let ids=new Set([...h,...s]);$("#reviewGrid").innerHTML=D.words.filter(w=>ids.has(String(w.id))).slice(0,100).map(card).join("")||`<div class="empty">أضف كلمات للمفضلة أو الصعبة لتظهر هنا.</div>`}
function renderLevelExams(){$("#levelExamGrid").innerHTML=Object.entries(D.levelExams).map(([l,x])=>`<article class="exam-level-card"><span class="badge">${l}</span><h3>${x.title}</h3><p>${x.note}</p><b>${x.duration}</b><ul>${x.sections.map(s=>`<li>${s}</li>`).join("")}</ul><button onclick="level='${l}';openTab('practice');renderPractice('mega')">ابدأ اختبار ${l}</button></article>`).join("")}
$("#searchBtn").onclick=()=>$("#overlay").classList.remove("hidden");$("#closeOverlay").onclick=()=>$("#overlay").classList.add("hidden");$("#overlay").onclick=e=>{if(e.target===$("#overlay"))$("#overlay").classList.add("hidden")};$("#globalSearch").oninput=e=>{let q=e.target.value.toLowerCase().trim();let rows=q?D.words.filter(w=>(w.word+" "+w.meaning+" "+w.theme).toLowerCase().includes(q)).slice(0,10):[];$("#searchResults").innerHTML=rows.map(w=>`<div class="feedback"><b class="de">${w.word}</b> — ${w.meaning}</div>`).join("")};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");
function renderAll(){updateProgress();renderUnits();renderVocab();renderDaily();renderGrammar();renderPron();renderReview();renderLevelExams();renderExam(exam)}renderAll();